### ISSUE TITLE
Coregister broken for different longitude domains

### ISSUE THREAD

**Issue by thomas-eldridge** [CCI-Tools/cate-core#330] opened 2017-08-17 10:53 UTC
### Expected behavior

When providing 'coregister' operation with a master and slave dataset, expected an output dataset with the spatial resolution of master. 

### Actual behavior

Operation crashes because domain of longitudes is not the same. 

### Steps to reproduce the problem

1. Open 'ESA Cloud Climate Change Initiative (Cloud_cci): ATSR2-AATSR monthly girdded cloud properties, version 2.0' (for period 2000-01-01 - 2001-01-01)
2. Open 'ESA Ozone Climte Change Initiative (Ozone CCI): Level 3 Total Ozone Merged Data Product, version 1' (for period 2000-01-01 - 2001-01-01)
3. Apply 'coregister' on the two open dataset resources. Error should occur

### Additional comments

Automatic longitude domain wrapping is the most obvious fix for this, but I also couldn't figure out how to do it myself (if I'd been working with the datasets in a python interpreter I would have simply added/subtracted from the longitude of relevant parts of the dataset - cannot find an operation for this in Cate and such an operation may be useful in general(?))

I also tried to see if the coregister operation would work on these datasets if I spatially subset them so that the longitude domains were comparable (i.e. for somewhere in the region 0-180). This also doesn't seem to work.

**Comment by JanisGailis** [comment] 2017-08-17 16:22
I suspect this should be handled during the normalization, when a dataset is being open.

**Comment by JanisGailis** [comment] 2017-09-22 10:25
These seem to be the exact same datasets that are used in our Use Case 9 demonstration script:
```
# Download some CCI Cloud data
cate ds copy esacci.CLOUD.mon.L3C.CLD_PRODUCTS.multi-sensor.multi-platform.ATSR2-AATSR.2-0.r1 --name CLOUD_2007 --time '2007-01-01,2007-03-31'
# Download some CCI Ozone data
cate ds copy esacci.OZONE.mon.L3.NP.multi-sensor.multi-platform.MERGED.fv0002.r1 --name OZONE_2007 --time '2007-01-01,2007-03-31'

# Start interactive session by initialising an empty workspace
# This will write a hidden directory .\.cate-workspace
cate ws init

# Open the Cloud and Ozone datasets and assign it to resources named "cloud" and "ozone"
cate res open cloud local.CLOUD_2007
cate res open ozone local.OZONE_2007

# Select the desired ECVs from the full datasets
cate res set ozone_tot select_var ds=@ozone var='O3_du_tot'
cate res set cloud_cfc select_var ds=@cloud var='cfc'

# Coregister "ozone_tot" with "cloud_cfc" and call the result "ozone_coreg"
cate res set ozone_coreg coregister ds_master=@cloud_cfc ds_slave=@ozone_tot
```

For these datasets, the lat/lon domain is the expected one - -90,90,-180,180, so I was not able to reproduce the problem.

Another note is that users should select only the variables they are interested in and for which resampling makes sense. Applying the coregistration on the full datasets would indeed create problems in Cate dev6 version with not being able to coregister n-dimensional datasets, a problem which you reported and that will be fixed in the next development release.

Further on, it would be helpful if you can make the issues a little bit more elaborate. For example, for this issue it would  have been helpful if you copied in the dataset IDs, as well as the exact parameters used to invoke the coregistration operation (e.g., which one was master, which one was slave dataset), so that we can make sure we're really trying to do the same thing with the same data!

**Comment by JanisGailis** [comment] 2017-09-22 10:26
Will be closed now, but subject to reopening if the problem persists!

**Closed by JanisGailis** 2017-09-22 10:26 UTC
Labels: cannot_reproduce, ops
